### ISSUE TITLE
GetFileno Promise Timeouts

### ISSUE THREAD

**Issue by zoopzorp** [sstativa/mfc-node#14]
The script today started timing out on the promise during the GetFileno function. I did a bit of debugging and it seems that the parts variable on line 94 is not filling correctly.

Here is what the websocket messages look like:

001943 0 0 138 13615307

I am unsure what they were before.

**Comment by zoopzorp** [comment]
It seems the script is functioning again, for reference, the websocket messages are now:

[2017-06-12T180622] [DEBUG] 00281 0 807514141 0 0 Guest41207
[2017-06-12T180622] [DEBUG] 001833 0 807514141 1 0
[2017-06-12T180622] [DEBUG] 001833 0 807514141 1 0
[2017-06-12T180622] [DEBUG] 020381 0 807514141 14 256 {%22msg%22:{%22arg1%22:1681,%22arg2%22:21,%22from%22:0,%22len%22:0,%22to%22:1,%22type%22:14},%22msglen%22:358449,%22opts%22:256,%22respkey%22:1451230428,%22serv%22:30,%22type%22:14}001833 0 807514141 1 1

I am unsure if it was something temporary on MFC's end or if they limited my IP address. The website was working at the time I opened the issue.

**Comment by zoopzorp** [comment]
It seems MFC is limiting IP addresses. The issue is occurring again, and this time, there is no response from the websocket. It connects fine, but does not receive any messages back within the 30 seconds before bluebird times it out. Extending the timeout does not help.

If I bind the outgoing websocket request to a different IP (adding {localAddress: "x.x.x.x"} as a final paramater to the end of the client.connect on line 107) the script functions fine.

Is there anything the script is doing that would look different from a normal browser that is allowing them to detect and seemingly temporarily block an IP?

**Comment by zoopzorp** [comment]
I was able to get the script working again by changing the server it communicates with to xchat79. I wonder if we should be cycling through the servers we talk to each time the main loop runs? Will wait for developer comments.

**Comment by grissom02** [comment]
this is the error on a OSX:

[2017-06-12T223106] [ERROR] { Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
