### ISSUE TITLE
dispatcher error

### ISSUE THREAD

**Issue by kkeller20** [sstativa/mfc-node#2]
Getting an error.  Please let me know how to get past this issue

` node main.js
/Media/mfc-node/main.js:485
dispatcher.onGet('/', function(req, res) {
           ^

TypeError: dispatcher.onGet is not a function
    at Object.<anonymous> (/Media/mfc-node/main.js:485:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3`

**Comment by kkeller20** [comment]
Found it, it is missing var dispatcher = new dispatcher(); in main.js

var dispatcher = require('httpdispatcher');
var dispatcher = new dispatcher();
