### ISSUE TITLE
Time out errors

### ISSUE THREAD

**Issue by H4rm10d** [sstativa/mfc-node#24]
[2017-06-29T194700] [ERROR] TimeoutError: operation timed out
    at afterTimeout (E:\...\mfc-node-master\node_modules\bluebird\js\main\timers.js:16:15)
    at Timeout.timeoutTimeout (E:\...\mfc-node-master\node_modules\bluebird\js\main\timers.js:59:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-06-29T194700] Done, will search for new models in 30 second(s).
[2017-06-29T194732] 1797 model(s) online
[2017-06-29T194732] soranaXo is away or in a private
[2017-06-29T194732] Done, will search for new models in 30 second(s).
[2017-06-29T194832] [ERROR] TimeoutError: operation timed out
    at afterTimeout (E:\...\mfc-node-master\node_modules\bluebird\js\main\timers.js:16:15)
    at Timeout.timeoutTimeout (E:\...\mfc-node-master\node_modules\bluebird\js\main\timers.js:59:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-06-29T194832] Done, will search for new models in 30 second(s).
[2017-06-29T194932] [ERROR] TimeoutError: operation timed out
    at afterTimeout (E:\...\mfc-node-master\node_modules\bluebird\js\main\timers.js:16:15)
    at Timeout.timeoutTimeout (E:\...\mfc-node-master\node_modules\bluebird\js\main\timers.js:59:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-06-29T194932] Done, will search for new models in 30 second(s).
[2017-06-29T195032] [ERROR] TimeoutError: operation timed out
    at afterTimeout (E:\...\mfc-node-master\node_modules\bluebird\js\main\timers.js:16:15)
    at Timeout.timeoutTimeout (E:\...\mfc-node-master\node_modules\bluebird\js\main\timers.js:59:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

If you need me to do some debug stuff let me know what to do.

**Comment by horacio9a** [comment]
I have a similar problem but since I do not use a server less than xchat58 I haven't that problem. Maybe it's not just about that?
You can test with my version MFC Recorder [code](https://codeload.github.com/horacio9a/mfc-node/zip/master)

**Comment by sstativa** [comment]
Are you sure you use the latest version of the script? I checked every server in the script and did not have any issue. My guess you either use old version of the script or it was some issue with myfreecams servers.

**Comment by SCG82** [comment]
I've also checked every server in the script. I do see the Timeout Error occasionally, but even those servers successfully negotiate 75% of the time over a 6 hours period.

**Comment by sstativa** [comment]
I made some changes in the code. It does not fix the Timeout Error, however, it minimise the impact.

**Comment by zoopzorp** [comment]
It seems after tonight's downtime MFC has changed the websocket authentication, here is what the mobile client sends after the hello now:

1 0 0 20080909 0 hash@guest:guest

where hash is a repeated value that is given to it by the server.

**Comment by SCG82** [comment]
sends:
```
hello fcserver
1 0 0 81 0 %7B%22err%22%3A0%2C%22start%22%3A1499516917190%2C%22stop%22%3A1499516917280%2C%22a%22%3A11263%2C%22time%22%3A1499516917%2C%22key%22%3A%225feb88f56e156c56c8055dcd3b8d4363%22%2C%22cid%22%3A%2287133aba%22%7D
0 0 0 0 0 -
```
receives: 
```
00090 0 0 0 1
004381 0 0 1 0 14d80df2150eeb3d5adaa0b889e9123b
```
sends:

```
1 0 0 20080909 0 14d80df2150eeb3d5adaa0b889e9123b@guest:guest
```

receives:
```
00281 0 305046559 0 0 Guest04389
001833 0 305046559 1 0001833 0 305046559 1 0
(more messages)
```
sends:
`44 305046559 0 1 0 -`

receives:
`(messages)`

sends every ~4 seconds:
`0 0 0 0 0 - `

url decoded 2nd sent message:
```
1 0 0 81 0 {"err":0,"start":1499516917190,"stop":1499516917280,"a":11263,"time":1499516917,"key":"5feb88f56e156c56c8055dcd3b8d4363","cid":"87133aba"}
```

**Comment by marabu88** [comment]
i think don't need update key each time.

**Comment by sstativa** [comment]
to SCG82,
You almost right with the steps, but you missed one at the beginning. When you open model's room in your browser, the page request a "challenge" from the server, solve it and send message back. If the solution is correct, then the server return the key, and only after that you can start authentication with that key.

I did not try to debug timeouts, therefore I don't know the origin. It might be some "maintenance" on MFC servers or may be they started to reject connection without a key and slowly upgrade their servers one by one.

I know how to do a proper login (it is one of the requirement if you want to record via rtmpdump), but solution is a "bit" complicated, therefore I don't want to include it in the code, but we will look how it goes.

**Comment by marabu88** [comment]
I think the problem is that now server blocking does not happen for every server, but for everyone at once, if too many requests from the same IP occur in a short period of time. Therefore, you need to minimize the number of requests to obtain a key.

**Comment by marabu88** [comment]
I looked at the log. I have an update every 30 seconds - after 5-8 requests to different servers for about 5 minutes, all servers are blocked, which lasts 30 minutes. Examine the client's changes for the browser. I believe that locking does not occur when you use it.

**Comment by jimmyoh** [comment]
Is the problem with keepalive ?

SCG82's comment on the repeating "0 0 0 0 0 -" every 4 seconds made me think...

Query the server, get  the key, Keep the connection alive.
Use the key until the server times out?
Grab a new key .....
I think they count the number of new keys given to an IP in a given time and block you on that.
The key should be good as long as the keepalive is going?

I was looking around....

var agent = new http.Agent({
  keepAlive: true,
  maxSockets: 1,
  keepAliveMsecs: 3000
})

https://stackoverflow.com/questions/28229044/http-keep-alive-in-node-js

I am totally lost in java script, or i'd try to implement this. 
although, I might try this in bash ;)

**Comment by sstativa** [comment]
Fixed.
