### ISSUE TITLE
Sime problems with some servers

### ISSUE THREAD

**Issue by marabu88** [sstativa/mfc-node#29]
Today the version with MFCAuto ended with an error (I forgot to save which one, but there was only information about the standard modules). After the restart, I found that the connection to the servers is sometimes very strange. Long wait, then message like this:

`Login handshake completed. Logged in as 'Guest94873' with sessionId 211372346`

And then .... nothing

What is this line of code for?

`.timeout(120000) // 2 mins`

What happens if there is no connection in 2 minutes? 

The previous version without MFCAuto worked stably continuously for several days until the servers began to be blocked :( But this version has gaps with stability. I do not know yet the reason is in this script or in the module MFCAuto. If possible, then check again if all possible errors are properly processed everywhere.

**Comment by sstativa** [comment]
MFCAuto has its own bugs that really hard to trace because they are related to "unpredictable" servers' behaviour. I just treat them as noncritical.

At start, MFCAuto connect to the randomly selected server, then wait for the list of the models, and  then the script proceed further. I had an issue sometimes when MFCAuto has never received the list of the models, therefore I made this timeout. If MFCAuto could not get the list of the models in 2 minutes the script will be terminated. In my case I have a daemon that restarts script when it fails.

The easiest way for you is too restart the script. The right way will be to add additional cycle at start that will force MFCAuto to reconnect to other server if the list of the models was not fulfilled in 2 mins.

I personally prefer to restart the script automatically, this also helps to deal with another "bug" of MFCAuto (it throws an exception on timeouts sometimes).

**Comment by grissom02** [comment]
I'm having this issue since 1 day ago I guess:

[2017-07-09T213007] Server listening on: 0.0.0.0:9080
[2017-07-09T213037] [ERROR] TimeoutError: operation timed out
    at afterTimeout (H:\isos\mfc-node-master\node_modules\bluebird\js\main\timers.js:16:15)
    at Timeout.timeoutTimeout (H:\isos\mfc-node-master\node_modules\bluebird\js\main\timers.js:59:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

any idea of what's going on?

**Comment by sstativa** [comment]
to **grissom02**

You have to update the script. MFC made some changes recently on their servers.

**Comment by grissom02** [comment]
thank you. Updated, but there is still a lot of timeouts from servers...

[07/09/2017 - 21:46:29] Server listening on: 0.0.0.0:9080
[07/09/2017 - 21:46:29] Connecting to MyFreeCams chat server xchat69...
[07/09/2017 - 21:48:29] [ERROR] TimeoutError: operation timed out
[07/09/2017 - 21:48:29] Server has not responded in over 2 minutes. Trying to reconnect now.
[07/09/2017 - 21:48:29] Disconnected from MyFreeCams.  Reconnecting in 15 seconds...
[07/09/2017 - 21:48:44] Connecting to MyFreeCams chat server xchat48...
[07/09/2017 - 21:50:44] Server has not responded in over 2 minutes. Trying to reconnect now.
[07/09/2017 - 21:50:44] Disconnected from MyFreeCams.  Reconnecting in 30 seconds...
[07/09/2017 - 21:51:14] Connecting to MyFreeCams chat server xchat44...

**Comment by sstativa** [comment]
With all changes on the servers, MFC started to ban users by their ip. Stop the script, wait for 30 min and try again.

**Comment by grissom02** [comment]
oh, that's sad. Thanks for the info!

**Comment by marabu88** [comment]
My daemon - it bat-file (i use windows 10) :)
```
:loop
node main.js
goto loop
```

Since mfc ban ip after 5-6 attempts to connect, it is necessary that all scripts work with a minimum number of restarts. If the error is uncritical and the connection to the server is not broken, then the script should continue to work. I think this is a task for the developer MFCAuto. But now debugging is a rather complex process :(

From my experience, if there is no connection at once, then it makes no sense to wait 2 minutes. You just need to forcefully terminate the script and start it again. It seems that some servers have problems.

**Comment by sstativa** [comment]
When I did this "workaround" there were problems with connections to servers. The problem was in "waitForModels", therefore I chose to wait for 2 mins and try again.

Probably, with all these timeouts from MFC servers this workaround should be replaces by something more appropriate.

**Comment by jimmyoh** [comment]
Hello all,

I got this error lastnight.
MFC was having issues again...
0 models online Etc....
200 models....
0 models .....

[07/11/2017 - 00:37:41] Done, will search for new models in 90 second(s).
[07/11/2017 - 00:39:11] 0 model(s) online
[07/11/2017 - 00:39:11] Done, will search for new models in 90 second(s).
[07/11/2017 - 00:40:29] Connecting to MyFreeCams chat server xchat79...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 207.229.75.34:8100
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1078:14)


Probably something simple ?

**Comment by Nailz1911** [comment]
Serverside issues. MFC itself was having problems https://twitter.com/MyFreeCams/status/884632861831245825

**Comment by jimmyoh** [comment]
Yes,
The program died on this...
It should be able to survive something like this ...
:)

Just trying to help

**Comment by Nailz1911** [comment]
Oh I see. gotcha!

**Comment by wylde780** [comment]
I'm experience similar issues listed above, however it seems like MFC app servers are blocking traffic from my IP. Frontend webservers try and load the list of models ( while viewing in chrome ) and the list fails to load consistently. When i email support the ban is usually cleared and the site performs normally again. So the question is .. what is triggering this event ? user_agent ? # of streams being captured ? I'm not sure

**Comment by jimmyoh** [comment]
Wylde780

Re-Install a fresh copy.
Save your config.yml

**Comment by wylde780** [comment]
jimmyoh 

Thanks for your suggestion, but it makes no sense to me. Functionally the application works the issue is on the MFC side. I fail to see how reinstalling an application on the client will remove an ip ban or denial of access on the server side.

**Comment by jimmyoh** [comment]
How old is your copy? More than a week ?

**Comment by sstativa** [comment]
The old app used to create a new connection every 30 seconds, the new app creates only one connection. 
If you got banned because of creating multiple connections for the short time, you will have to wait at least 30 minutes to get your ban removed.

**Comment by wylde780** [comment]
Sstaitva thanks for explain this and thanks for the fix .. i did notice the changes once i updated. Note for others that once it was able to eventually login as a guest. It didn't start capturing right away. I needed to restart main.js  and at this time the ban was removed and a connection was able to be established immediately thus capturing started.

Jimmyoh thank you

**Comment by jimmyoh** [comment]
Hello all,
I think my DSL disconnected last night.
And It crashed with.
[07/13/2017 - 00:13:23] Server has not responded in over 2 minutes. Trying to reconnect now.
[07/13/2017 - 00:13:23] Disconnected from MyFreeCams.  Reconnecting in 15 seconds...
[07/13/2017 - 00:13:27] 0 model(s) online
[07/13/2017 - 00:13:27] Done, will search for new models in 90 second(s).
[07/13/2017 - 00:13:38] Connecting to MyFreeCams chat server xchat58...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN xchat58.myfreecams.com:8100
    at Object.exports._errnoException (util.js:907:11)
    at errnoException (dns.js:32:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
