### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by naksitrallid** [sstativa/mfc-node#31]
fresh clone doesn't work for me anymore. i see this when i run nodejs main.js

```
/mfc/node_modules/MFCAuto/lib/Client.js:18
    constructor(username = "guest", password = "guest") {
                         ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/mfc/node_modules/MFCAuto/lib/index.js:6:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/mfc/main.js:16:11)
    at Module._compile (module.js:409:26)
```
npm install did perform fine
```
user@vm04:~/mfc# npm install
underscore@1.8.3 node_modules/underscore

promise-queue@2.2.3 node_modules/promise-queue

colors@1.1.2 node_modules/colors

string@3.3.3 node_modules/string

httpdispatcher@2.1.0 node_modules/httpdispatcher
└── mime@1.3.6

filewalker@0.1.3 node_modules/filewalker
└── fqueue@0.0.0

bluebird@2.11.0 node_modules/bluebird

mkdirp@0.5.1 node_modules/mkdirp
└── minimist@0.0.8

MFCAuto@4.0.0 node_modules/MFCAuto
├── xmlhttprequest@1.8.0
└── load@1.0.2

js-yaml@3.9.0 node_modules/js-yaml
├── esprima@4.0.0
└── argparse@1.0.9 (sprintf-js@1.0.3)

mv@2.1.1 node_modules/mv
├── ncp@2.0.0
└── rimraf@2.4.5 (glob@6.0.4)

moment@2.18.1 node_modules/moment
```
i use nodejs 4.8.2

**Comment by sstativa** [comment]
MFCAuto was updated recently. It was "compiled" using ES6 specification which was in use starting from node v6. You should either update your node to v6 or (if this is not a case) downgrade MFCAuto by using a command
`npm install ZombieAlex/MFCAuto#v3.4.6`
