### ISSUE TITLE
Add redundancy for when MFCAuto fails

### ISSUE THREAD

**Issue by zoopzorp** [sstativa/mfc-node#32]
It seems MFC or MFCAuto had some issues and the mfc-node script doesn't recover gracefully:

```
[07/20/2017 - 12:39:11] [ERROR] { sid: xxxxx,
  uid: xxxxx,
  vs: 0,
  pid: 1,
  hidecs: true,
  rc: 16,
  camserv: 1327 }
[07/20/2017 - 12:39:11] 26 model(s) online
[07/20/2017 - 12:39:11] Done, will search for new models in 50 second(s).
[07/20/2017 - 12:39:37] Server has not responded in over 2 minutes. Trying to reconnect now.
[07/20/2017 - 12:39:37] Disconnected from MyFreeCams.  Reconnecting in 15 seconds...
[07/20/2017 - 12:39:52] Connecting to MyFreeCams chat server xchat31...
[07/20/2017 - 12:40:01] [DEBUG] Start new cycle
[07/20/2017 - 12:40:01] 0 model(s) online
[07/20/2017 - 12:40:01] Done, will search for new models in 50 second(s).
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND xchat31.myfreecams.com xchat31.myfreecams.com:8100
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
[07/20/2017 - 12:40:34] Server listening on: 0.0.0.0:9080
(node:17159) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: getaddrinfo ENOTFOUND www.myfreecams.com www.myfreecams.com:80
[07/20/2017 - 12:42:34] [ERROR] TimeoutError: operation timed out
```

The script does nothing further afterwards. Even having the script fully exit upon error would be fine as my bash script would restart it. I believe the unhandled event is inside MFCAuto so we may not be able to fix that, but hopefully the TimeoutError can be handled and worked around.

**Comment by sstativa** [comment]
My local copy does exactly what you've just described, it exists on unhandled error or timeout (if MFCauto don't resolve `connectAndWaitForModels` in 2 minutes).
I was not aware that git version does not do it.

**Comment by forsomefun** [comment]
is there a modded version of mfcauto we can use?
