### ISSUE TITLE
client disconnections are not handled as they once were

### ISSUE THREAD

**Issue by toiletmummysalad** [sstativa/mfc-node#34]
If I disconnect, after about 3-4 minutes there is attempt to reconnect in the next 15 seconds, no matter if I have or don't have internet access this fails with a different error and no reconnection happens.

If I disconnect and get a new IP address in that disconnect the node stops and this is what it pops:

```
Done, will search for new models in 30 second(s).
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)


```

This did not happen in the previous versions. Everything else works perfectly now though.

**Comment by forsomefun** [comment]
Having the same issue
Sometimes it seems to be random. 
For example every night now after running for a few hours at around 10pm this error will come up at around 4am when I check the logs in the morning.

**Comment by sstativa** [comment]
Unfortunately, there is no simple solution. 
These errors are thrown by MFCAuto module that handles communication with MFC servers. Even if I create some workaround on top of MFCAuto I'll not be able to guarantee that the script works correct after 1st caught error.

The best approach so far will be to use some "demons" that automatically restart the script after fail. Look at this for example [forever].

**Comment by toiletmummysalad** [comment]
This tool sounds great! Btw, this only happens if I get a disconnect from my internet provider and it is really annoying, it also did not happen in the past, it just tried to connect and connect until it could, but the recorder now works as great as it worked around March - April, so I do not mind.

**Comment by forsomefun** [comment]
What should we  set the minuptime and spinsleeptime to?
Or is the 1000ms a good number

**Comment by sstativa** [comment]
to __forsomefun__

I'm not sure what are you talking about.

I've just noticed I lost the link in my previous message. Probably it led you to the wrong solution. Look at [forever](https://www.npmjs.com/package/forever) module for node.js.

**Comment by forsomefun** [comment]
--minUptime      Minimum uptime (millis) for a script to not be considered "spinning"
    --spinSleepTime  Time to wait (millis) between launches of a spinning script.

**Comment by forsomefun** [comment]
Do you think their would be a way to hide the cmd windows that the program makes?

**Comment by jimmyoh** [comment]
Hello,
Mine died last night with this.

[08/09/2017 - 01:04:44] Done, will search for new models in 90 second(s).
[08/09/2017 - 01:05:11] Disconnected from MyFreeCams.  Reconnecting in 15 seconds...
[08/09/2017 - 01:05:26] Connecting to MyFreeCams websocket server xchat22...
[08/09/2017 - 01:05:41] Server has not responded in over 2 minutes. Trying to reconnect now.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: closed before the connection is established
    at WebSocket.close (/home/jimmyoh/mfc-node-master/mfc-node-master/node_modules/MFCAuto/node_modules/ws/lib/WebSocket.js:270:28)
    at EventEmitter.<anonymous> (/home/jimmyoh/mfc-node-master/mfc-node-master/node_modules/MFCAuto/lib/Client.js:645:41)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)



Just adding my 0.02$

Jim

**Comment by grissom02** [comment]
I'm getting this since yesterday:

`[08/11/2017 - 01:57:26] Connecting to MyFreeCams websocket server xchat75...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND xchat75.myfreecams.com xchat75.myfreecams.com:8080
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

H:\isos\v3\mfc-node-master>node main.js
[08/11/2017 - 20:08:03] Server listening on: 0.0.0.0:9080
[08/11/2017 - 20:08:03] Connecting to MyFreeCams websocket server xchat80...
[08/11/2017 - 20:08:18] Server has not responded in over 2 minutes. Trying to reconnect now.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: closed before the connection is established
    at WebSocket.close (H:\isos\v3\mfc-node-master\node_modules\ws\lib\WebSocket.js:270:28)
    at EventEmitter.<anonymous> (H:\isos\v3\mfc-node-master\node_modules\MFCAuto\lib\Client.js:645:41)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)`

**Comment by sstativa** [comment]
The latest [MFCAuto](https://github.com/ZombieAlex/MFCAuto/commit/5fa5166e4871ea12e1bed34b5b20ede482b471e7) tries to handle this issue.
