### ISSUE TITLE
Error after upgrade...

### ISSUE THREAD

**Issue by grissom02** [sstativa/mfc-node#35]
Hello, 
I download the code for upgrade, and put back my model list from the old config.yml, but when I run node main.js I'm getting this error:

`H:\mfc-node-master>node main.js

H:\mfc-node-master\node_modules\js-yaml\lib\js-yaml\loader.js:168
  throw generateError(state, message);
  ^
YAMLException: duplicated mapping key at line 12, column -1362:
    models:
    ^
    at generateError (H:\mfc-node-master\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (H:\mfc-node-master\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at storeMappingPair (H:\mfc-node-master\node_modules\js-yaml\lib\js-yaml\loader.js:307:7)
    at readBlockMapping (H:\mfc-node-master\node_modules\js-yaml\lib\js-yaml\loader.js:1070:9)
    at composeNode (H:\mfc-node-master\node_modules\js-yaml\lib\js-yaml\loader.js:1331:12)
    at readDocument (H:\mfc-node-master\node_modules\js-yaml\lib\js-yaml\loader.js:1493:3)
    at loadDocuments (H:\mfc-node-master\node_modules\js-yaml\lib\js-yaml\loader.js:1549:5)
    at load (H:\mfc-node-master\node_modules\js-yaml\lib\js-yaml\loader.js:1566:19)
    at Object.safeLoad (H:\mfc-node-master\node_modules\js-yaml\lib\js-yaml\loader.js:1584:10)
    at Object.<anonymous> (H:\mfc-node-master\main.js:25:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)`

Any idea of what I'm doing wrong??

**Comment by sstativa** [comment]
`npm install`

**Comment by grissom02** [comment]
Actually I did and the error remained. But... after I download the zip again and extract in a new folder, editing the config file I've notice I did paste the model's list in the end of the file instead below the model: line.
So, sorry. My mistake. It's working now. Thank you!
