### ISSUE TITLE
Problem starting up?

### ISSUE THREAD

**Issue by jimmyoh** [sstativa/mfc-node#36]
Hello, 
I'm up to date with everything.
npm install
But when i call node main.js I get

/home/jimmyoh/mfc-node-master/node_modules/MFCAuto/lib/Client.js:19
    constructor(username = "guest", password = "guest", useWebSockets = false) {
                         ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jimmyoh/mfc-node-master/node_modules/MFCAuto/lib/index.js:6:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jimmyoh/mfc-node-master/main.js:16:11)
    at Module._compile (module.js:409:26)

The ^ is pointed at the first "="
Am I missing something ?

Also, I Suck at JS ;)
Jimbo

**Comment by jimmyoh** [comment]
Opps, nodejs Ver 6....
opensuse, defaults to ver 4.73.....
