### ISSUE TITLE
Can't setup mfc-node

### ISSUE THREAD

**Issue by yoyosnart** [sstativa/mfc-node#40]
pls,help:(

D:\Metadata\mfc-node-master>cmd
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

D:\Metadata\mfc-node-master>node main.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Metadata\mfc-node-master\main.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

D:\Metadata\mfc-node-master>

**Comment by sstativa** [comment]
`npm install` ?
