### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by xz3513** [sstativa/mfc-node#49]
After following the instructions exactly, I get this message when running `node main.js`:
```
X:\mfc-node-master\node_modules\MFCAuto\lib\Model.js:713
Model.rawListeners = Model.eventsForAllModels.rawListeners.bind(Model.eventsForAllModels);
                                                          ^

TypeError: Cannot read property 'bind' of undefined
    at Object.<anonymous> (X:\mfc-node-master\node_modules\MFCAuto\lib\Model.js:713:59)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (X:\mfc-node-master\node_modules\MFCAuto\lib\Client.js:15:17)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
```
I have tried both with Node.js 6.13.0 and 8.9.4 and get the same message.

**Comment by cakeod** [comment]
I'm receiving the same error, not sure what is going on.

**Comment by Ignignokt-07** [comment]
From https://github.com/ZombieAlex/MFCAuto/issues/19
"v5.0.0 requires Node 9.4.0 or above #19"

https://nodejs.org/download/release/v9.5.0/

Updating node.js via the installer resolved the error.

**Comment by sstativa** [comment]
The latest version of MFCAuto requires node.js v9.4.0 or higher. I've updated Readme file to reflect this requirement.
