### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by papano24** [sstativa/mfc-node#52]
Greetings,

Having an issue with running your node. It worked for me in the past, however, recently I was running into a websocket issue and the node was constantly closing out. I saw that you had a new version and I attempted to install that one and encountered the error below. After many attempts I uninstalled the new version and installed v2 and received the same error. Any clues????

C:\mfc-node-2>node -v
v9.2.0

C:\mfc-node-2>node main.js
C:\mfc-node-2\node_modules\MFCAuto\lib\Model.js:733
Model.rawListeners = Model.eventsForAllModels.rawListeners.bind(Model.eventsForA
llModels);
                                                           ^

TypeError: Cannot read property 'bind' of undefined
    at Object.<anonymous> (C:\mfc-node-2\node_modules\MFCAuto\lib\Model.js:733:6
0)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\mfc-node-2\node_modules\MFCAuto\lib\Client.js:15:1
7)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)

**Comment by sstativa** [comment]
Minimum requirement is Node.js v9.4.0
