### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by jjis2018** [sstativa/mfc-node#55]
Does this work on Linux? Tryimng to install it on Linux Mint Cinnamon, I get this error running node main.js:

/home/donnie/mfc-node-master/node_modules/MFCAuto/lib/Client.js:68
    constructor(username = "guest", password = "guest", options = {}) {
                         ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/donnie/mfc-node-master/node_modules/MFCAuto/lib/index.js:6:10)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/donnie/mfc-node-master/main.js:15:11)
    at Module._compile (module.js:410:26)

**Comment by jjis2018** [comment]
8.9.4 or 9.4? I have the latest LTS 8.11.1 installed
