### ISSUE TITLE
Error when adding a model

### ISSUE THREAD

**Issue by SearchAndDestroy** [sstativa/mfc-node#6]
I am getting 
[ERROR] TypeError: "options" must be a string or an object, got number instead.
when I try to add a model either via the interface or the localhost:9080/models/include?nm=name

She is correctly indicated as "To Include" but I get the error in the console

**Comment by Damianonymous** [comment]
https://github.com/sstativa/mfc-node/commit/0dc175997fce6c6422f8515f071ada0ff8542df6

**Comment by Damianonymous** [comment]
https://github.com/sstativa/mfc-node/blob/0dc175997fce6c6422f8515f071ada0ff8542df6/main.js

**Comment by Damianonymous** [comment]
https://github.com/sstativa/mfc-node/commit/0dc175997fce6c6422f8515f071ada0ff8542df6

**Comment by SearchAndDestroy** [comment]
I just cloned it and I am uptodate with the temp fix

**Comment by metalgeekstl** [comment]
just installed and getting same error, I assume with the fix included?

**Comment by SearchAndDestroy** [comment]
Yes with the fix included
It's working but as soon as I add a model I am getting the error

**Comment by marabu88** [comment]
i have this error also if try add/remove models

```
2017-04-19T222152] [DEBUG] Save changes in config.yml
[2017-04-19T222152] [ERROR] TypeError: "options" must be a string or an object, got number instead.
    at getOptions (fs.js:53:11)
    at Object.fs.writeFileSync (fs.js:1312:13)
    at G:\MFCNode\mfc-node-master\main.js:257:12
    at tryCatcher (G:\MFCNode\mfc-node-master\node_modules\bluebird\js\main\util.js:26:23)
    at Function.Promise.attempt.Promise.try (G:\MFCNode\mfc-node-master\node_modules\bluebird\js\main\method.js:31:24)
    at selectMyModels (G:\MFCNode\mfc-node-master\main.js:162:9)
    at G:\MFCNode\mfc-node-master\main.js:413:14
    at tryCatcher (G:\MFCNode\mfc-node-master\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (G:\MFCNode\mfc-node-master\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (G:\MFCNode\mfc-node-master\node_modules\bluebird\js\main\promise.js:584:18)
    at Async._drainQueue (G:\MFCNode\mfc-node-master\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (G:\MFCNode\mfc-node-master\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (G:\MFCNode\mfc-node-master\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-04-19T222152] Done, will search for new models in 30 second(s).
```

**Comment by marabu88** [comment]
p.s. I think this is problem with new Node. I just fix it:
```
-fs.writeFileSync('config.yml', yaml.safeDump(config), **0,** 'utf8'); 
+fs.writeFileSync('config.yml', yaml.safeDump(config), 'utf8');
```

**Comment by metalgeekstl** [comment]
Works for me now. Thanks.

**Comment by SearchAndDestroy** [comment]
Nice, thanks :) It's recording for me too
